services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - helpdesk

  service-discovery:
    container_name: 'service-discovery'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    environment:
      - PORT=8761
    ports:
      - "8761:8761"
    expose:
      - 8761
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - helpdesk

  config-server:
    container_name: 'config-server'
    build:
      context: ./config-server
      dockerfile: Dockerfile
    environment:
      - CONFIG_SERVER_URI=${CONFIG_REPO_URI}
      - CONFIG_SERVER_USERNAME=${CONFIG_REPO_USER}
      - CONFIG_SERVER_PASSWORD=${CONFIG_REPO_TOKEN}
      - EUREKA_URI=http://service-discovery:8761/eureka
    depends_on:
      service-discovery:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - helpdesk

  api-gateway:
    container_name: 'api-gateway'
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_URI=http://service-discovery:8761/eureka
      - CONFIG_SERVER_URI=http://config-server:8888
    ports:
      - "8765:8765"
    expose:
      - 8765
    depends_on:
      service-discovery:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - helpdesk

networks:
  helpdesk:
    name: helpdesk
    driver: bridge
    attachable: true