services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: user-service
    volumes:
      - ./.data:/data/db
