spring:
  application:
    name: 'helpdesk-bff'
  cloud:
    config:
      uri: 'config-server'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 9000